services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netlogix\Nximageoptimizer\:
    resource: '../Classes/*'

  Netlogix\Nximageoptimizer\EventListener\ImageOptimizer:
    tags:
      - name: event.listener
        identifier: 'optimizeImage'
        method: 'optimizeImage'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileProcessingEvent

  Netlogix\Nximageoptimizer\EventListener\WebpCreator:
    tags:
      - name: event.listener
        identifier: 'createWebpVersion'
        method: 'createWebpVersion'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileProcessingEvent
