name: PHP TYPO3 Extension

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    name: TYPO3 ${{ matrix.typo3}} on PHP ${{ matrix.php }}

    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0, 8.1]
        typo3: [10.4, 11.5]

        exclude:
          # do not run TYPO3 10.4 on PHP 8
          - php: 8.0
            typo3: 10.4
          # do not run TYPO3 10.4 on PHP 8.1
          - php: 8.1
            typo3: 10.4

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: pdo, sqlite3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install TYPO3 core
        run: composer require typo3/cms-core="^${{ matrix.typo3 }}" -W

      - name: Unit Tests
        run: XDEBUG_MODE=coverage .Build/bin/phpunit -c phpunit.xml

      - name: Functional Tests
        run: XDEBUG_MODE=coverage .Build/bin/phpunit -c phpunit_functional.xml