name: Test TYPO3 Extension

on: [ push, pull_request ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-20.04

    name: TYPO3 ${{ matrix.typo3}} on PHP ${{ matrix.php }}

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4, 8.0, 8.1 ]
        typo3: [ 10.4, 11.5 ]

        exclude:
          # do not run TYPO3 10.4 on PHP 8
          - php: 8.0
            typo3: 10.4
          # do not run TYPO3 10.4 on PHP 8.1
          - php: 8.1
            typo3: 10.4

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: pdo, sqlite3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-php${{ matrix.php }}-typo3${{ matrix.typo3 }}


      - name: Install TYPO3 core
        run: composer require typo3/cms-core="^${{ matrix.typo3 }}" -W

      - name: Unit Tests
        run: .Build/bin/phpunit -c phpunit.xml

      - name: Functional Tests
        run: .Build/bin/phpunit -c phpunit_functional.xml

      # merge reports of unit tests and functional tests, then generate cobertura file for reporter
      # without this step the reporter will see both tests as different code packages and the coverage report is wrong
      - name: Merge Coverage Report
        run: .Build/bin/phpcov merge --cobertura .Build/logs/cobertura.xml .Build/logs/coverage/

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: .Build/logs/cobertura.xml
          badge: true
          # there are not enough tests yet
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md